### PR TITLE
Fix errors in examples

### PR DESCRIPTION
**Pull request by ebatsell**

### CODE REVIEW

**Comment by ebatsell** [comment]
@mvines some small improvements :)

**Comment by mvines** [comment]
oops, thanks for these fixes!

**Comment by mvines** [comment]
If you rebase over 9555474d2a1b6ad07ddda115eea273271523fd45 then the clippy issues reported by CI here should now be resolved

**Comment by mvines** [comment]
heh one more clippy link in the examples. latest rust update enabled https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args

if you've had enough, I can take over though

**Comment by mvines** [comment]
ty sir! 🖖🏼

**Pull request merged**
